generator0:	generator0.cc
	g++ -Wall generator0.cc -o generator0

generator1:	generator1.cc
	g++ -Wall generator1.cc -o generator1

generator2:	generator2.cc
	g++ -Wall generator2.cc -o generator2

generator3:	generator3.cc
	g++ -Wall generator3.cc -o generator3

generator4:	generator4.cc
	g++ -Wall generator4.cc -o generator4

generator5:	generator5.cc
	g++ -Wall generator5.cc -o generator5

generator6:	generator6.cc
	g++ -Wall generator6.cc -o generator6

generator7:	generator7.cc
	g++ -Wall generator7.cc -o generator7

generator8:	generator8.cc
	g++ -Wall generator8.cc -o generator8

generator9:	generator9.cc
	g++ -Wall generator9.cc -o generator9

generator10:	generator10.cc
	g++ -Wall generator10.cc -o generator10
